% -------------------------------------------------------------------------
% merge.m 
%
% -------------------------------------------------------------------------
% Description:
%
% It copies all files generated by loci.m for every single animal experiment
% and merges them into a common folder that represents the complete kinematic
% information of the corresponding experimental situation (genotype,
% stimulus intensity, etc.). That is useful as a means of centralizing and
% tidying up the data for subsequent analysis.
% If preferred, one can still focus on only one particular trajectory.
% -------------------------------------------------------------------------

clear
close all

% ------------------------------------------------------------------------
% Directories
dirGo='/Users/agomez/Desktop/supplementary/datademo/';
dirFinal='/Users/agomez/Desktop/supplementary/datademo/allExperiments/';
mkdir(dirFinal);
cd(dirGo);

filesArray=dir(strcat(dirGo,'experiment*'));
maxFolder=length(filesArray);

for folder=1:maxFolder

cd(dirGo)
folderName=filesArray(folder).name;
cd(folderName);

% Files to copy
% positions
destination1=strcat(dirFinal,'coordinates', num2str(sprintf('%03d',folder)),'.mat');
destination2=strcat(dirFinal,'trajectory', num2str(sprintf('%03d',folder)),'.jpeg');
% other properties
destination3=strcat(dirFinal,'properties', num2str(sprintf('%03d',folder)),'.mat');
% callibration reference
destination4=strcat(dirFinal,'reference', num2str(sprintf('%03d',folder)),'.mat');
% skeleton and perimeter
destination5=strcat(dirFinal,'skel', num2str(sprintf('%03d',folder)),'.mat');
destination6=strcat(dirFinal,'contour', num2str(sprintf('%03d',folder)),'.mat');

% Files and location to paste
copyfile('coordinates.mat',destination1);
copyfile('trajectory.jpeg',destination2);
copyfile('properties.mat',destination3);
copyfile('reference.mat',destination4);
copyfile('skel.mat',destination5);
copyfile('contour.mat',destination6);

end

% dirOut='/Users/agomez/Desktop/';
% cd(dirOut);

